#pragma once

#include <glm/glm.hpp>
#include <cstdint>
#include <string>
#include <vector>

// Runtime CPU sampler for the biome map generated by tools/biome_preprocess.
//
// Pixel encoding (see BiomeGenerator::saveBiomeMap):
//   R = zone id (BiomeZone), G = sub-zone, B = settlement proximity, A = 255
//
// Sampling convention: the map covers content space [0, terrainSize] with
// texel (x, y) = floor(content / terrainSize * resolution), matching the
// tile_generator rasterization convention (nearest texel, no half-texel
// offset). World coordinates are converted via WorldCoords::worldToContent.
class BiomeMap {
public:
    // Zone ids written by tools/biome_preprocess (BiomeZone)
    enum class Zone : uint8_t {
        Sea = 0,
        Beach = 1,
        ChalkCliff = 2,
        SaltMarsh = 3,
        River = 4,
        Wetland = 5,
        Grassland = 6,
        Agricultural = 7,
        Woodland = 8,
        Unknown = 255
    };

    static std::string getBiomeMapPath(const std::string& cacheDir) {
        return cacheDir + "/biome_map.png";
    }

    bool loadFromPng(const std::string& path, float terrainSize);

    bool isLoaded() const { return width_ > 0; }
    uint32_t resolution() const { return width_; }

    // Sample by world-space XZ (centered origin)
    Zone zoneAtWorld(float worldX, float worldZ) const;
    // Settlement proximity 0..1 (0 = at a settlement, 1 = >= 2km away)
    float settlementProximityAtWorld(float worldX, float worldZ) const;

private:
    size_t texelIndex(float worldX, float worldZ) const;

    std::vector<uint8_t> rgba_;
    uint32_t width_ = 0;
    uint32_t height_ = 0;
    float terrainSize_ = 16384.0f;
};
